### PR TITLE
doc: initial sync of nodejs/open-standards members

### PR DESCRIPTION
**Pull request by joyeecheung**
Refs: https://github.com/nodejs/admin/issues/213
Refs: https://github.com/nodejs/TSC/issues/583

I've sent invitations to people nominated/indicated that they are willing to help in https://github.com/nodejs/TSC/issues/583 to join the team @nodejs/open-standards 

Three members pending the acceptance of the invitation because they are not yet members of this organization: @ladyleet @littledan @kenchris

cc @MylesBorins ( who is on vacation, but I feel that I should still cc you..sorry ;) )

### CODE REVIEW

**Comment by ladyleet** [comment]
@joyeecheung joined thx!

**Review by ljharb — APPROVED** [review]

**Review by MylesBorins — APPROVED** [review]
Lgtm

Would be interested in seeing some copy around membership rules as well... But it can come in. A follow up

**Review by benjamingr — APPROVED** [review]
Sure. As I said in the original issue, I think there are people here who are more qualified (I've mostly only had a few contributions to whatwg and a failed tc39 proposal  myself) and I'm not sure I have time to engage due to personal commitments.

That said, I am extremely interested in promoting Node.js's use case in standards bodies and would like to see how I can help.

Would be great to clarify what sort of commitment this team would require? I would rather make sure I can attend all meetings and participate meaningfully :)

**Review by BridgeAR — APPROVED** [review]

**Review by TimothyGu — APPROVED** [review]

**Review by devsnek — APPROVED** [review]

**Review by apapirovski — APPROVED** [review]

**Comment by kenchris** [comment]
> Three members pending the acceptance of the invitation because they are not yet members of this organization: @ladyleet @littledan @kenchris

What do I need to do?

**Comment by MylesBorins** [comment]
@kenchris looks like you've done it... landing PR

**Comment by kenchris** [comment]
@mylesborins should I be in the list you committed?

**Comment by MylesBorins** [comment]
@kenchris ptal --> https://github.com/nodejs/open-standards/pull/5

**Pull request merged**
